# Workflow for building and deploying a Hugo site to GitHub Pages
name: Deploy Hugo to GitHub Pages

on:
  # Runs on pushes targeting the default branch
  push:
    branches:
      - main  # Set a branch to deploy
  pull_request:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow one concurrent deployment
concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

# Default to bash
defaults:
  run:
    shell: bash

jobs:
  # Build Job
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo + hugo themes
        uses: actions/checkout@v3
        with:
          submodules: recursive  # Fetch Hugo themes (true OR recursive)
          fetch-depth: 1    # Fetch all history for .GitInfo and .Lastmod
      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          #hugo-version: 'latest'
          hugo-version: '0.91.2'
          extended: true
      - name: Build Hugo page
        run: hugo \
          --minify \
          --baseURL "${{ steps.pages.outputs.base_url }}/"
      - name: Upload artifacts
        uses: actions/upload-pages-artifact@v1
        with:
          path: ./public
  
  # Deployment job
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1